In [12]:
from itertools import combinations as cb
list=["a","b","c","d","e"]
count = 1 
for i in range (1,len(list)+1):
    comb= cb(list,i)
    print (i)
    
    
    for j in comb:
        print(j)
        print ("count ",count,j)
        count=count+1

1
('a',)
count  1 ('a',)
('b',)
count  2 ('b',)
('c',)
count  3 ('c',)
('d',)
count  4 ('d',)
('e',)
count  5 ('e',)
2
('a', 'b')
count  6 ('a', 'b')
('a', 'c')
count  7 ('a', 'c')
('a', 'd')
count  8 ('a', 'd')
('a', 'e')
count  9 ('a', 'e')
('b', 'c')
count  10 ('b', 'c')
('b', 'd')
count  11 ('b', 'd')
('b', 'e')
count  12 ('b', 'e')
('c', 'd')
count  13 ('c', 'd')
('c', 'e')
count  14 ('c', 'e')
('d', 'e')
count  15 ('d', 'e')
3
('a', 'b', 'c')
count  16 ('a', 'b', 'c')
('a', 'b', 'd')
count  17 ('a', 'b', 'd')
('a', 'b', 'e')
count  18 ('a', 'b', 'e')
('a', 'c', 'd')
count  19 ('a', 'c', 'd')
('a', 'c', 'e')
count  20 ('a', 'c', 'e')
('a', 'd', 'e')
count  21 ('a', 'd', 'e')
('b', 'c', 'd')
count  22 ('b', 'c', 'd')
('b', 'c', 'e')
count  23 ('b', 'c', 'e')
('b', 'd', 'e')
count  24 ('b', 'd', 'e')
('c', 'd', 'e')
count  25 ('c', 'd', 'e')
4
('a', 'b', 'c', 'd')
count  26 ('a', 'b', 'c', 'd')
('a', 'b', 'c', 'e')
count  27 ('a', 'b', 'c', 'e')
('a', 'b', 'd', 'e')
count  28 ('a', 'b', 'd', 'e')
('a', 'c', 'd', 'e')
count  29 ('a', 'c', 'd', 'e')
('b', 'c', 'd', 'e')
count  30 ('b', 'c', 'd', 'e')
5
('a', 'b', 'c', 'd', 'e')
count  31 ('a', 'b', 'c', 'd', 'e')

In [13]:
import pandas as pd

In [23]:
# !pip install mlxtend
from mlxtend.preprocessing import TransactionEncoder

In [19]:
df = [['Milk', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
           ['Dill', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
           ['Milk', 'Apple', 'Kidney Beans', 'Eggs'],
           ['Milk', 'Unicorn', 'Corn', 'Kidney Beans', 'Yogurt'],
           ['Corn', 'Onion', 'Onion', 'Kidney Beans', 'Ice cream', 'Eggs']]

In [24]:
te = TransactionEncoder()
te_data= te.fit(df).transform(df)
te_df = pd.DataFrame(te_data, columns= te.columns_)
te_df

,Apple,Corn,Dill,Eggs,Ice cream,Kidney Beans,Milk,Nutmeg,Onion,Unicorn,Yogurt
0,False,False,False,True,False,True,True,True,True,False,True
1,False,False,True,True,False,True,False,True,True,False,True
2,True,False,False,True,False,True,True,False,False,False,False
3,False,True,False,False,False,True,True,False,False,True,True
4,False,True,False,True,True,True,False,False,True,False,False

In [26]:
from mlxtend.frequent_patterns import apriori
apriori(te_df, min_support=0.7,use_colnames=True)

   support              itemsets
0      0.8                (Eggs)
1      1.0        (Kidney Beans)
2      0.8  (Kidney Beans, Eggs)

In [30]:
!pip install google.colab

Collecting google.colab
  Using cached google-colab-1.0.0.tar.gz (72 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting google-auth~=1.4.0 (from google.colab)
  Obtaining dependency information for google-auth~=1.4.0 from https://files.pythonhosted.org/packages/56/80/369a47c28ce7d9be6a6973338133d073864d8efbb62747e414c34a3a5f4f/google_auth-1.4.2-py2.py3-none-any.whl.metadata
  Using cached google_auth-1.4.2-py2.py3-none-any.whl.metadata (3.0 kB)
Collecting ipykernel~=4.6.0 (from google.colab)
  Obtaining dependency information for ipykernel~=4.6.0 from https://files.pythonhosted.org/packages/18/c3/76775a650cae2e3d9c033b26153583e61282692d9a3af12a3022d8f0cefa/ipykernel-4.6.1-py3-none-any.whl.metadata
  Using cached ipykernel-4.6.1-py3-none-any.whl.metadata (981 bytes)
Collecting ipython~=5.5.0 (from google.colab)
  Obtaining dependency information for ipython~=5.5.0 from https://files.pythonhosted.org/packages/07/63/c987612bcf82c56eaacaf6bf01e31e53a244a0a3a0fb036ec5adc377e0fe/ipython-5.5.0-py3-none-any.whl.metadata
  Using cached ipython-5.5.0-py3-none-any.whl.metadata (4.3 kB)
Collecting notebook~=5.2.0 (from google.colab)
  Obtaining dependency information for notebook~=5.2.0 from https://files.pythonhosted.org/packages/96/a2/d951ebb7855743f989287486ded73cd3f66915c3ecd9c5c5a0c7ca12377a/notebook-5.2.2-py2.py3-none-any.whl.metadata
  Using cached notebook-5.2.2-py2.py3-none-any.whl.metadata (1.8 kB)
Collecting six~=1.12.0 (from google.colab)
  Obtaining dependency information for six~=1.12.0 from https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl.metadata
  Using cached six-1.12.0-py2.py3-none-any.whl.metadata (1.9 kB)
Collecting pandas~=0.24.0 (from google.colab)
  Using cached pandas-0.24.2.tar.gz (11.8 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

  error: subprocess-exited-with-error

  python setup.py egg_info did not run successfully.
  exit code: 1

  [15 lines of output]
  C:\Users\aarek\AppData\Local\Temp\pip-install-r9jhkv_5\pandas_578f31d8d4dd4aea94f662388c039b2d\setup.py:12: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    import pkg_resources
  C:\Users\aarek\anaconda3\Lib\site-packages\setuptools\__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
  !!

          ********************************************************************************
          Requirements should be satisfied by a PEP 517 installer.
          If you are using pip, you can try `pip install --use-pep517`.
          ********************************************************************************

  !!
    dist.fetch_build_eggs(dist.setup_requires)
  error in pandas setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after version specifier)
      pytz >= 2011k
           ~~~~~~~^
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

In [31]:
from google.colab import drive
drive.mount("/content/drive")

ModuleNotFoundError: No module named 'google.colab'